[versions]
# Search in the project for: "this region should be removed completely when plugin is updated to 8.1.0-alpha09 and upper"
android-gradle-plugin = "8.1.4"
androidx-appcompat = "1.6.1"
androidx-compose-bom = "2023.10.01"
androidx-compose-compiler = "1.5.3"
androidx-constraintlayout = "2.1.4"
androidx-core = "1.12.0"
androidx-preference = "1.2.1"
androidx-recyclerview = "1.3.2"
detekt = "1.23.4"
firebase-bom = "32.6.0"
firebase-crashlytics-gradle = "2.9.9"
java = "20"
glide = "4.16.0"
google-android-material = "1.10.0"
google-services = "4.4.0"
hyperion = "0.9.37"
ksp = "1.9.10-1.0.13"
koin = "3.5.0"
kotlin = "1.9.10"
leak-canary = "2.12"
room = "2.6.0"
rxjava2-rxandroid = "2.1.1"
rxjava2-rxjava = "2.2.21"
rxbinding3 = "3.1.0"
timber = "5.0.1"
triplet-play = "3.8.6"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-preference = { module = "androidx.preference:preference-ktx", version.ref = "androidx-preference" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
glide-core = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-ksp = { module = "com.github.bumptech.glide:ksp", version.ref = "glide" }
google-android-material = { group = "com.google.android.material", name = "material", version.ref = "google-android-material" }
hyperion-core = { module = "com.willowtreeapps.hyperion:hyperion-core", version.ref = "hyperion" }
hyperion-attr = { module = "com.willowtreeapps.hyperion:hyperion-attr", version.ref = "hyperion" }
hyperion-build-config = { module = "com.willowtreeapps.hyperion:hyperion-build-config", version.ref = "hyperion" }
hyperion-disk = { module = "com.willowtreeapps.hyperion:hyperion-disk", version.ref = "hyperion" }
hyperion-geiger-counter = { module = "com.willowtreeapps.hyperion:hyperion-geiger-counter", version.ref = "hyperion" }
hyperion-measurement = { module = "com.willowtreeapps.hyperion:hyperion-measurement", version.ref = "hyperion" }
hyperion-phoenix = { module = "com.willowtreeapps.hyperion:hyperion-phoenix", version.ref = "hyperion" }
hyperion-recorder = { module = "com.willowtreeapps.hyperion:hyperion-recorder", version.ref = "hyperion" }
hyperion-shared-preferences = { module = "com.willowtreeapps.hyperion:hyperion-shared-preferences", version.ref = "hyperion" }
hyperion-timber = { module = "com.willowtreeapps.hyperion:hyperion-timber", version.ref = "hyperion" }
koin = { module = "io.insert-koin:koin-android", version.ref = "koin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
leak-canary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leak-canary" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-rxjava2 = { module = "androidx.room:room-rxjava2", version.ref = "room" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }
rxbinding = { module = "com.jakewharton.rxbinding3:rxbinding", version.ref = "rxbinding3" }
rxjava2-rxandroid = { module = "io.reactivex.rxjava2:rxandroid", version.ref = "rxjava2-rxandroid" }
rxjava2-rxjava = { module = "io.reactivex.rxjava2:rxjava", version.ref = "rxjava2-rxjava" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

# Testing
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

# Dependencies of the included build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "android-gradle-plugin" }
firebase-crashlytics-gradlePlugin = { group = "com.google.firebase", name = "firebase-crashlytics-gradle", version.ref = "firebase-crashlytics-gradle" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

[bundles]
hyperion = [
    "hyperion-core",
    "hyperion-attr",
    "hyperion-build-config",
    "hyperion-disk",
    "hyperion-geiger-counter",
    "hyperion-measurement",
    "hyperion-phoenix",
    "hyperion-recorder",
    "hyperion-shared-preferences",
    "hyperion-timber"
]
rxjava = ["rxjava2-rxandroid", "rxjava2-rxjava", "rxbinding"]

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics-gradle" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
triplet-play = { id = "com.github.triplet.play", version.ref = "triplet-play" }

# Debts plugins defined in build-logic
debts-android-application = { id = "debts.android.application", version.ref = "android-gradle-plugin" }
debts-android-application-compose = { id = "debts.android.application.compose", version.ref = "android-gradle-plugin" }
debts-android-library = { id = "debts.android.library", version.ref = "android-gradle-plugin" }
debts-android-library-compose = { id = "debts.android.library.compose", version = "android-gradle-plugin" }
debts-android-room = { id = "debts.android.room", version.ref = "room" }
debts-android-application-firebase = { id = "debts.android.application.firebase", version.ref = "firebase-crashlytics-gradle" }
debts-android-image-loader = { id = "debts.android.image.loader", version.ref = "glide" }
